name: Trigger auto deployment for vald-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vald-bot-AutoDeployTrigger-41ca184a-56cc-40b1-959d-b402c5ca798a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.VALDBOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VALDBOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VALDBOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: valdbotregistry.azurecr.io
          registryUsername: ${{ secrets.VALDBOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VALDBOT_REGISTRY_PASSWORD }}
          containerAppName: vald-bot
          resourceGroup: valdbot-rg
          imageToBuild: valdbotregistry.azurecr.io/vald-bot:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


